### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by SiriChandanaGarimella** [oss-slu/esp#105]
**Is your feature request related to a problem? Please describe.**
Currently, the About page has minimal information, making it difficult for new users to understand how to use it effectively. Additionally, users cannot navigate back to the Home page by clicking the app logo/title.

**Describe the solution you'd like**
- Enhance the About page with:
  1. Example inputs and outputs to demonstrate the app's functionality
  2. Step-by-step how-to guides for common use cases
  3. Tutorial videos showing the main flow of the application
  4. Documentation of the key features
- Implement navigation functionality:
  1. Make both the app logo and title clickable
  2. Users should be redirected to the Home page when clicking on either logo or title
  3. Include proper hover states to indicate clickability

**Comment by M-Ravali** [comment]
Hi, I would like to contribute to this project. Can you assign this or any issue of the frontend to me?

**Comment by SiriChandanaGarimella** [comment]
hi @M-Ravali, thank you for your interest in contributing to this project. This issue requires a better understanding of the overall application and might not be a good first issue. Please look into #103, which can be a good first issue to start with.
