### ISSUE TITLE
Upload the ORCA/Gaussian text files on the client component

### ISSUE THREAD

**Issue by rkarmuri** [oss-slu/esp#31]
Now that we set up the connection between the Angular and Flask components. We want the user to be able to upload the input files in text format through the user interface. We are to restrict uploading any other file formats on the user interface.

Success criteria for this issue:

- [x] The Angular component allows users to upload files to the server component.
- [x] No CORS issues should occur during the file upload process.
- [x] Ensure the Flask server receives the text file from the client component.
- [x] The server component acknowledges that the files are uploaded successfully.
- [x] The server component sends the acknowledgment to the client component and the client component displays the message on the UI.

**Comment by mkalal6** [comment]
Work in progress. Implementing similarities from prior sprint to this sprint in exchange of text to input files.

**Comment by rkarmuri** [comment]
We can successfully upload the text files on the client component and send them to the flask component.
