### ISSUE TITLE
Retrieve the data from the ORCA files

### ISSUE THREAD

**Issue by rkarmuri** [oss-slu/esp#36]
The frontend UI now accepts the ORCA text file and the entries to retrieve the data. Implement the functionality to retrieve the data based on the input entered on the front end. The input is sent to the Flask backend, the Flask backend takes the input, processes the data based on the input, and sends it to the angular component in a tabular form. Update the Angular user interface to display the processed data returned from the Flask backend.

Success criteria:

- [x] The front end sends the uploaded ORCA text file and entered criteria to the Flask backend for processing.
- [x] The Flask backend successfully receives the uploaded ORCA text file and the entered criteria from the front end.
- [x] The Flask backend processes the data based on the received input criteria, extracting relevant information from the ORCA text file.
- [ ] Processed data from the Flask backend is sent back to the Angular component in a tabular form.
- [ ] The Angular user interface is updated to display the processed data returned from the Flask backend.

**Comment by SiriChandanaGarimella** [comment]
The processed data from the Flask backend is sent back to the Angular component as a document now. The angular user interface downloads a word document by clicking on the "Convert" button.
