### ISSUE TITLE
BUG: On Windows, file path is displayed as the file tag instead of filename

### ISSUE THREAD

**Issue by SiriChandanaGarimella** [oss-slu/esp#73]
**Describe the bug**
On Windows system, the full file path is displayed as the file tag instead of just the filename after uploading a file.

**To Reproduce**
1. Open the application on a Windows system and navigate to the URL http://localhost:3000/temp
2. Click on "Choose File" to select a file
3. Select any ORCA log file as the input file
4. Click on 'Upload'
4. Observe the name in the file tag that is displayed under 'Uploaded Files:' 

**Expected behavior**
Only the filename should be displayed, not the full file path.

**Screenshots**

**Additional context**
This issue appears to be specific to Windows system

**Acceptance Criteria**
1. When a file is selected on a Windows system, only the filename (e.g., "document.txt") is displayed, not the full path.
2. The fix should not affect the correct display of filenames on other operating systems.
3. The actual file path should still be correctly sent to the server for processing.
4. The fix should work for files selected from different directories on the Windows system.
5. Add/update the related unit test cases with the code changes.

**Comment by tanishq-singh-2407** [comment]
Can I work on this?
